//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyfordController {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Manual : global::System.Configuration.ApplicationSettingsBase {
        
        private static Manual defaultInstance = ((Manual)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Manual())));
        
        public static Manual Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I 1.0 500\r\nO 1.5 500\r\nL 1.25 500\r\nI 1.5 500\r\nO 1 500\r\nR 1.25 500\r\nI \r\nW 0")]
        public string PartingThinSteel {
            get {
                return ((string)(this["PartingThinSteel"]));
            }
            set {
                this["PartingThinSteel"] = value;
            }
        }
    }
}
